### ISSUE TITLE
Fehler beim Ausführen des Containers

### ISSUE THREAD

**Issue by hroedel** [jugendpresse/docker-antragsgruen#9]
Hey, ich versuche gerade ein Antragsgrün mit Docker aufzusetzen. Leider bekomme ich, wenn ich den Container starte, folgenden Fehler: 

`Fatal error: Uncaught Error: Class "app\components\UrlHelper" not found in /var/www/html/models/settings/AntragsgruenApp.php:106 Stack trace: #0 /var/www/html/config/web.php(30): app\models\settings\AntragsgruenApp->__construct('') #1 /var/www/html/web/index.php(49): require('/var/www/html/c...') #2 {main} thrown in /var/www/html/models/settings/AntragsgruenApp.php on line 106`

Meine compose.yml sieht wie folgt aus: 
```
name: antragsgruen
services:
  antragsgruen:
    environment:
      APACHE_FQDN: '"localhost:8080"'
      TIMEZONE: '"Europe/Berlin"'
    image: devopsansiblede/antragsgruen:latest
    networks:
      internal: null
    ports:
      - mode: ingress
        target: 80
        published: "8080"
        protocol: tcp
  database:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_DATABASE: antragsgruen
      MARIADB_ROOT_PASSWORD: testing
    image: mariadb:11.7.2
    networks:
      internal: null
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
        volume: {}
networks:
  internal:
    name: antragsgruen_internal
volumes:
  database:
    name: antragsgruen_database
```

Ist der Fehler bekannt und wie kann er behoben werden?
